name: skin_termo_ai
description: "AI-powered skin disease prediction app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  shimmer: ^3.0.0
  animate_do: ^3.1.2
  shared_preferences: ^2.2.2
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  smooth_page_indicator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
